#ifndef SOUND_SCRAPER_H
#define SOUND_SCRAPER_H

/* Generated by cbindgen from core/crates/core/src/ffi.rs. Do not edit. */

#include <stdint.h>
#include <stdbool.h>

/*
 Bits for `SsTagEdit::set_mask`: which fields the edit changes.
 */
#define SS_TAG_TITLE (1 << 0)

#define SS_TAG_ARTIST (1 << 1)

#define SS_TAG_ALBUM (1 << 2)

#define SS_TAG_ALBUM_ARTIST (1 << 3)

#define SS_TAG_DATE (1 << 4)

#define SS_TAG_TRACK (1 << 5)

#define SS_TAG_GENRE (1 << 6)

#define SS_TAG_COMMENT (1 << 7)

/*
 Samples at or below this level (-60 dBFS) count as silence.
 */
#define THRESHOLD 0.001

/*
 Recorder state as seen from C.
 */
typedef enum SsRecorderState {
  SS_RECORDER_STATE_IDLE = 0,
  SS_RECORDER_STATE_RECORDING = 1,
  SS_RECORDER_STATE_PAUSED = 2,
  SS_RECORDER_STATE_FINALIZING = 3,
} SsRecorderState;

/*
 Result of a fallible call. On `SS_STATUS_ERROR`, `ss_last_error_message`
 describes the failure.
 */
typedef enum SsStatus {
  SS_STATUS_OK = 0,
  SS_STATUS_ERROR = 1,
} SsStatus;

typedef enum SsRecorderEventKind {
  /*
   `state` changed.
   */
  SS_RECORDER_EVENT_KIND_STATE_CHANGED = 0,
  /*
   About 10 Hz while recording or paused: `elapsed_ms`, `peak`, `rms`.
   */
  SS_RECORDER_EVENT_KIND_PROGRESS = 1,
  /*
   A recording was finalized at `path`.
   */
  SS_RECORDER_EVENT_KIND_FINISHED = 2,
  /*
   Recording failed; see `message`.
   */
  SS_RECORDER_EVENT_KIND_ERROR = 3,
  /*
   `player_state` changed.
   */
  SS_RECORDER_EVENT_KIND_PLAYER_STATE_CHANGED = 4,
  /*
   About 10 Hz while playing, and after loads, seeks and stops:
   `position_ms`, `duration_ms`, levels.
   */
  SS_RECORDER_EVENT_KIND_PLAYER_PROGRESS = 5,
  /*
   Playback failed; see `message`.
   */
  SS_RECORDER_EVENT_KIND_PLAYER_ERROR = 6,
} SsRecorderEventKind;

/*
 Player state as seen from C.
 */
typedef enum SsPlayerState {
  /*
   Nothing loaded.
   */
  SS_PLAYER_STATE_EMPTY = 0,
  /*
   Loaded, not playing.
   */
  SS_PLAYER_STATE_STOPPED = 1,
  SS_PLAYER_STATE_PLAYING = 2,
  SS_PLAYER_STATE_PAUSED = 3,
} SsPlayerState;

typedef enum SsCoverEdit {
  SS_COVER_EDIT_KEEP = 0,
  SS_COVER_EDIT_REMOVE = 1,
  /*
   Embed the JPEG/PNG at `cover_path`.
   */
  SS_COVER_EDIT_SET = 2,
} SsCoverEdit;

typedef enum SsTagVersion {
  SS_TAG_VERSION_ID3V24 = 0,
  SS_TAG_VERSION_ID3V23 = 1,
} SsTagVersion;

/*
 Opaque list of apps from `ss_audio_apps_list`.
 */
typedef struct SsAudioAppList SsAudioAppList;

/*
 Opaque window drag or resize in progress (see core/crates/layout). Free
 with `ss_layout_gesture_end`.
 */
typedef struct SsLayoutGesture SsLayoutGesture;

/*
 Opaque handle to the recordings library (`~/Music/Sound Scraper`).
 Its functions may be called from any thread.
 */
typedef struct SsLibrary SsLibrary;

/*
 Opaque recorder handle, which also plays recordings back (`ss_player_*`).
 Create with `ss_recorder_create`, free with `ss_recorder_destroy`. Its
 functions may be called from any thread.
 */
typedef struct SsRecorder SsRecorder;

/*
 Opaque list from `ss_library_list`.
 */
typedef struct SsRecordingList SsRecordingList;

/*
 Opaque visualizer handle: draws the live analysis of the recording, or
 of playback. Create
 with `ss_vis_create`, free with `ss_vis_destroy`. One per view; use it
 from one thread at a time.
 */
typedef struct SsVis SsVis;

/*
 A recorder event. Pointers are valid only during the callback.
 */
typedef struct SsRecorderEvent {
  enum SsRecorderEventKind kind;
  enum SsRecorderState state;
  /*
   Recorded time, excluding pauses.
   */
  uint64_t elapsed_ms;
  /*
   Linear levels (0..1) over the last interval, the louder channel's
   peak and the channels' mean RMS (`peak_left` etc. give each channel).
   They keep moving while paused.
   */
  float peak;
  float rms;
  float peak_left;
  float peak_right;
  float rms_left;
  float rms_right;
  /*
   UTF-8; non-NULL for `SS_RECORDER_EVENT_KIND_FINISHED` only.
   */
  const char *path;
  /*
   UTF-8; non-NULL for `SS_RECORDER_EVENT_KIND_ERROR` and
   `SS_RECORDER_EVENT_KIND_PLAYER_ERROR` only.
   */
  const char *message;
  /*
   The player's state, position and the loaded file's duration (all
   events).
   */
  enum SsPlayerState player_state;
  uint64_t position_ms;
  uint64_t duration_ms;
} SsRecorderEvent;

/*
 Receives recorder events, on a recorder thread or the calling thread.
 It must return quickly and must not call back into the same recorder.
 */
typedef void (*SsRecorderCallback)(const struct SsRecorderEvent *event, void *user_data);

/*
 An app that can be recorded on its own. Strings are UTF-8 and owned by the
 list they came from.
 */
typedef struct SsAudioApp {
  uint32_t pid;
  const char *name;
  /*
   NULL when the process has no bundle ID.
   */
  const char *bundle_id;
  bool is_playing;
} SsAudioApp;

/*
 Outcome of `ss_capture_test_wav`. Free `path` with `ss_capture_report_free`.
 */
typedef struct SsCaptureReport {
  /*
   UTF-8 path of the WAV file that was written.
   */
  char *path;
  uint64_t frames;
  uint32_t sample_rate;
  uint16_t channels;
  /*
   Largest absolute sample; 0 means the recording was silent.
   */
  float peak;
} SsCaptureReport;

/*
 One recording. Strings are UTF-8 and owned by the list.
 */
typedef struct SsRecording {
  /*
   Name inside the recordings folder; pass it to the other library calls.
   */
  const char *file_name;
  const char *path;
  /*
   ID3 title, or the file name without extension.
   */
  const char *title;
  /*
   NULL when not tagged.
   */
  const char *artist;
  /*
   NULL when not tagged.
   */
  const char *album;
  uint64_t duration_ms;
  uint64_t size_bytes;
  /*
   Unix time in milliseconds.
   */
  int64_t recorded_at_ms;
} SsRecording;

/*
 Called (debounced, on a watcher thread) when recordings are added,
 removed or changed on disk.
 */
typedef void (*SsLibraryCallback)(void *user_data);

/*
 A recording's editable tags. Strings are UTF-8, NULL when not set, and
 owned by this struct; free it with `ss_tags_free`.
 */
typedef struct SsTags {
  const char *title;
  const char *artist;
  const char *album;
  const char *album_artist;
  /*
   "YYYY", "YYYY-MM" or "YYYY-MM-DD".
   */
  const char *date;
  const char *genre;
  const char *comment;
  /*
   Track number; 0 when not set.
   */
  uint32_t track;
  /*
   Path of the embedded front cover, extracted to the app's cover cache
   (NULL when there is no cover).
   */
  const char *cover_path;
} SsTags;

/*
 A tag change for one or more recordings. Fields whose bit is not in
 `set_mask` are left alone; a set field with a NULL or empty string (or
 `track` 0) is cleared.
 */
typedef struct SsTagEdit {
  uint32_t set_mask;
  const char *title;
  const char *artist;
  const char *album;
  const char *album_artist;
  const char *date;
  const char *genre;
  const char *comment;
  uint32_t track;
  enum SsCoverEdit cover;
  const char *cover_path;
  enum SsTagVersion version;
} SsTagEdit;

/*
 Input rates LAME accepts without resampling.
 */
#define SUPPORTED_RATES { 8000, 11025, 12000, 16000, 22050, 24000, 32000, 44100, 48000, }

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Core version as a NUL-terminated UTF-8 string with static lifetime.
 The caller must not free it.
 */
const char *ss_version(void);

/*
 Creates a recorder in the Idle state that saves to the default recordings
 folder. Never returns NULL.
 */
struct SsRecorder *ss_recorder_create(void);

/*
 Destroys a recorder, finalizing any recording in progress. NULL is a no-op.

 # Safety
 `recorder` must be NULL or a handle from `ss_recorder_create` that has
 not already been destroyed, with no other call on it in progress.
 */
void ss_recorder_destroy(struct SsRecorder *recorder);

/*
 Current state of `recorder`; Idle when `recorder` is NULL. Never blocks.

 # Safety
 `recorder` must be NULL or a live handle from `ss_recorder_create`.
 */
enum SsRecorderState ss_recorder_state(const struct SsRecorder *recorder);

/*
 Recorded time in milliseconds, excluding pauses. Never blocks.

 # Safety
 `recorder` must be NULL or a live handle from `ss_recorder_create`.
 */
uint64_t ss_recorder_elapsed_ms(const struct SsRecorder *recorder);

/*
 Sets (or with NULL, clears) the event callback, for recorder and player
 events. Only while the recorder is Idle.

 # Safety
 `recorder` must be a live handle; `user_data` must stay valid, and be
 usable from any thread, until the callback is replaced or the recorder
 is destroyed.
 */
enum SsStatus ss_recorder_set_callback(struct SsRecorder *recorder,
                                       SsRecorderCallback callback,
                                       void *user_data);

/*
 Starts recording one app (`app_pid` non-zero) or all system audio
 (`app_pid` 0) to a new `.mp3.part` in the recordings folder, unloading
 whatever the player had loaded. May block while macOS asks for the
 audio-capture permission; call off the UI thread.

 # Safety
 `recorder` must be NULL or a live handle from `ss_recorder_create`.
 */
enum SsStatus ss_recorder_start(struct SsRecorder *recorder, uint32_t app_pid);

/*
 Pauses: the file and encoder stay open and incoming audio is dropped.

 # Safety
 `recorder` must be NULL or a live handle from `ss_recorder_create`.
 */
enum SsStatus ss_recorder_pause(struct SsRecorder *recorder);

/*
 Resumes after `ss_recorder_pause`.

 # Safety
 `recorder` must be NULL or a live handle from `ss_recorder_create`.
 */
enum SsStatus ss_recorder_resume(struct SsRecorder *recorder);

/*
 Stops and finalizes (flush, Xing/LAME tag, ID3 tags, rename to `.mp3`).
 Blocks until done. On success `*out_path` (if not NULL) receives the
 file's UTF-8 path, to be freed with `ss_string_free`.

 # Safety
 `recorder` must be NULL or a live handle; `out_path` must be NULL or
 writable.
 */
enum SsStatus ss_recorder_stop(struct SsRecorder *recorder, char **out_path);

/*
 Loads a recording (any MP3) for playback, stopped at the start,
 replacing what was loaded. Not while recording.

 # Safety
 `recorder` must be NULL or a live handle; `path` NUL-terminated UTF-8.
 */
enum SsStatus ss_player_load(struct SsRecorder *recorder, const char *path);

/*
 Stops playback and forgets the loaded file. Blocks until the output
 device is released.

 # Safety
 `recorder` must be NULL or a live handle.
 */
enum SsStatus ss_player_unload(struct SsRecorder *recorder);

/*
 Plays (or resumes) the loaded file through the default output device.
 Not while recording.

 # Safety
 `recorder` must be NULL or a live handle.
 */
enum SsStatus ss_player_play(struct SsRecorder *recorder);

/*
 Pauses playback.

 # Safety
 `recorder` must be NULL or a live handle.
 */
enum SsStatus ss_player_pause(struct SsRecorder *recorder);

/*
 Stops playback and rewinds to the start.

 # Safety
 `recorder` must be NULL or a live handle.
 */
enum SsStatus ss_player_stop(struct SsRecorder *recorder);

/*
 Moves playback to `position_ms` (clamped to the file), keeping the state.

 # Safety
 `recorder` must be NULL or a live handle.
 */
enum SsStatus ss_player_seek(struct SsRecorder *recorder, uint64_t position_ms);

/*
 The player's state; Empty when `recorder` is NULL. Never blocks.

 # Safety
 `recorder` must be NULL or a live handle.
 */
enum SsPlayerState ss_player_state(const struct SsRecorder *recorder);

/*
 Playback position in milliseconds. Never blocks.

 # Safety
 `recorder` must be NULL or a live handle.
 */
uint64_t ss_player_position_ms(const struct SsRecorder *recorder);

/*
 The loaded file's duration in milliseconds (0 when nothing is loaded).
 Never blocks.

 # Safety
 `recorder` must be NULL or a live handle.
 */
uint64_t ss_player_duration_ms(const struct SsRecorder *recorder);

/*
 Finishes `.mp3.part` files left in the recordings folder by a crash.
 Returns how many were recovered, or -1 on error. Call at startup, before
 any recording starts.
 */
int32_t ss_recover_partial_recordings(void);

/*
 Frees a string returned by this library. NULL is a no-op.

 # Safety
 `s` must be NULL or a string from this library not already freed.
 */
void ss_string_free(char *s);

/*
 Message for the last `SS_STATUS_ERROR` returned on this thread. Valid until
 the next failing call on the same thread; the caller must not free it.
 */
const char *ss_last_error_message(void);

/*
 Apps with audio processes, those playing sound first. Free with
 `ss_audio_app_list_free`. Never returns NULL.
 */
struct SsAudioAppList *ss_audio_apps_list(void);

/*
 Number of apps in `list` (0 for NULL).

 # Safety
 `list` must be NULL or a live list from `ss_audio_apps_list`.
 */
size_t ss_audio_app_list_len(const struct SsAudioAppList *list);

/*
 App at `index`, or NULL when out of range. Valid until the list is freed.

 # Safety
 `list` must be NULL or a live list from `ss_audio_apps_list`.
 */
const struct SsAudioApp *ss_audio_app_list_get(const struct SsAudioAppList *list, size_t index);

/*
 Frees a list from `ss_audio_apps_list`. NULL is a no-op.

 # Safety
 `list` must be NULL or a list that has not already been freed.
 */
void ss_audio_app_list_free(struct SsAudioAppList *list);

/*
 Records `seconds` of audio to a WAV file in the recordings folder: one
 app's audio when `app_pid` is non-zero, otherwise all system audio.
 Blocks for the duration, so call it off the UI thread.

 # Safety
 `out_report` must point to writable memory for one `SsCaptureReport`.
 */
enum SsStatus ss_capture_test_wav(uint32_t app_pid,
                                  double seconds,
                                  struct SsCaptureReport *out_report);

/*
 Frees the strings inside a report filled by `ss_capture_test_wav`.

 # Safety
 `report` must be NULL or a report filled by `ss_capture_test_wav` that has
 not already been freed.
 */
void ss_capture_report_free(struct SsCaptureReport *report);

/*
 Opens the default library, creating the folder and index if needed.
 Returns NULL on failure (see `ss_last_error_message`).
 */
struct SsLibrary *ss_library_open(void);

/*
 Closes a library (stopping its watcher). NULL is a no-op.

 # Safety
 `library` must be NULL or a handle from `ss_library_open` not already
 destroyed, with no other call on it in progress.
 */
void ss_library_destroy(struct SsLibrary *library);

/*
 Rescans the folder and returns the recordings, newest first. Free with
 `ss_recording_list_free`. Returns NULL on failure.

 # Safety
 `library` must be NULL or a live handle from `ss_library_open`.
 */
struct SsRecordingList *ss_library_list(struct SsLibrary *library);

/*
 Number of recordings in `list` (0 for NULL).

 # Safety
 `list` must be NULL or a live list from `ss_library_list`.
 */
size_t ss_recording_list_len(const struct SsRecordingList *list);

/*
 Recording at `index`, or NULL when out of range. Valid until the list is freed.

 # Safety
 `list` must be NULL or a live list from `ss_library_list`.
 */
const struct SsRecording *ss_recording_list_get(const struct SsRecordingList *list, size_t index);

/*
 Frees a list from `ss_library_list`. NULL is a no-op.

 # Safety
 `list` must be NULL or a list not already freed.
 */
void ss_recording_list_free(struct SsRecordingList *list);

/*
 Renames a recording (sanitized, `.mp3` kept, " (2)" on collision; the
 ID3 title follows if it still matched the old name). On success
 `*out_file_name` (if not NULL) receives the new file name, to be freed
 with `ss_string_free`.

 # Safety
 `library` must be a live handle; `file_name` and `new_name` must be
 NUL-terminated UTF-8; `out_file_name` must be NULL or writable.
 */
enum SsStatus ss_library_rename(struct SsLibrary *library,
                                const char *file_name,
                                const char *new_name,
                                char **out_file_name);

/*
 Moves a recording to the Trash / Recycle Bin.

 # Safety
 `library` must be a live handle; `file_name` must be NUL-terminated UTF-8.
 */
enum SsStatus ss_library_trash(struct SsLibrary *library, const char *file_name);

/*
 Shows the recording selected in Finder / Explorer.

 # Safety
 `library` must be a live handle; `file_name` must be NUL-terminated UTF-8.
 */
enum SsStatus ss_library_reveal(struct SsLibrary *library, const char *file_name);

/*
 Starts watching the folder; `callback(user_data)` fires on changes.
 NULL callback stops watching.

 # Safety
 `library` must be a live handle; `user_data` must stay valid, and be
 usable from any thread, until the callback is replaced or the library
 is destroyed.
 */
enum SsStatus ss_library_set_callback(struct SsLibrary *library,
                                      SsLibraryCallback callback,
                                      void *user_data);

/*
 Reads a recording's tags (and extracts its cover). Returns NULL on
 failure (see `ss_last_error_message`).

 # Safety
 `library` must be a live handle; `file_name` must be NUL-terminated UTF-8.
 */
const struct SsTags *ss_library_read_tags(struct SsLibrary *library, const char *file_name);

/*
 Frees tags from `ss_library_read_tags`. NULL is a no-op.

 # Safety
 `tags` must be NULL or a pointer from `ss_library_read_tags` not already freed.
 */
void ss_tags_free(const struct SsTags *tags);

/*
 Applies `edit` to each of `count` recordings (bulk edit), atomically per
 file. All names are checked before anything is written.

 # Safety
 `library` must be a live handle; `file_names` must point to `count`
 NUL-terminated UTF-8 strings; `edit` must be valid, with its strings
 NULL or NUL-terminated UTF-8.
 */
enum SsStatus ss_library_write_tags(struct SsLibrary *library,
                                    const char *const *file_names,
                                    size_t count,
                                    const struct SsTagEdit *edit);

/*
 The settings as JSON (see core/crates/core/src/settings.rs):
 `{"recordingsDir": string|null, "quality": "cbr128"|"cbr192"|"cbr256"|
 "cbr320"|"vbr0"|"vbr2", "id3Version": "2.4"|"2.3", "lastSource":
 null|{"kind":"system"}|{"kind":"app","id":string|null,"name":string},
 "trimSilence": bool}` (and the skin settings),
 plus `"effectiveRecordingsDir"`. Free with `ss_string_free`.
 */
char *ss_settings_get(void);

/*
 Validates and saves settings JSON (unknown keys are ignored; missing
 keys take defaults). Call `ss_library_apply_settings` afterwards.

 # Safety
 `json` must be NUL-terminated UTF-8.
 */
enum SsStatus ss_settings_set(const char *json);

/*
 Points the library at the recordings folder from the saved settings.

 # Safety
 `library` must be a live handle from `ss_library_open`.
 */
enum SsStatus ss_library_apply_settings(struct SsLibrary *library);

/*
 Creates a visualizer for `recorder`'s audio, drawing the default preset.
 It stays valid after the recorder is destroyed (it then shows the idle
 look). NULL if `recorder` is NULL.

 # Safety
 `recorder` must be NULL or a live handle from `ss_recorder_create`.
 */
struct SsVis *ss_vis_create(const struct SsRecorder *recorder);

/*
 Sets the preset: one entry of a resolved skin's `visualizer.presets`, as
 JSON (`{"style": "bars"|"scope"|"mirror"|"radial"|"fire", "bands",
 "color", "gradient", "peak", "gap", "lineWidth", "background", "grid",
 "line", "decay", "beat"}`; colors as #hex).

 # Safety
 `vis` must be a live handle; `json` NUL-terminated UTF-8.
 */
enum SsStatus ss_vis_set_preset(struct SsVis *vis, const char *json);

/*
 Draws the latest frame, or the idle look when nothing is recording, into
 `rgba`: premultiplied RGBA, `width` × `height` pixels, `len` bytes (at
 least width × height × 4), with `unit` pixels per skin point. Returns
 true while a recording is live (keep redrawing), false when idle (the
 idle look needs drawing only once) or on bad arguments.

 # Safety
 `vis` must be a live handle; `rgba` must point to `len` writable bytes.
 */
bool ss_vis_render(struct SsVis *vis,
                   uint32_t width,
                   uint32_t height,
                   float unit,
                   uint8_t *rgba,
                   size_t len);

/*
 Whether a recording (active or paused) or playback (playing or paused)
 is live, so frames change. Cheap;
 lets a view skip redrawing the idle look.

 # Safety
 `vis` must be NULL or a live handle.
 */
bool ss_vis_is_live(const struct SsVis *vis);

/*
 Destroys a visualizer. NULL is a no-op.

 # Safety
 `vis` must be NULL or a handle from `ss_vis_create` not yet destroyed.
 */
void ss_vis_destroy(struct SsVis *vis);

/*
 Starts dragging panel `id`. `scene_json` is `{"panels": [{"id", "x",
 "y", "w", "h", "visible"}], "screens": [{"x", "y", "w", "h"}]}` in
 global points, origin top left, y down; screens are work areas. Dragging
 "main" moves its docked chain; other panels move alone. NULL on failure.

 # Safety
 `scene_json` and `id` must be NUL-terminated UTF-8.
 */
struct SsLayoutGesture *ss_layout_drag_begin(const char *scene_json, const char *id);

/*
 Starts resizing panel `id` by its right and bottom edges, no smaller than
 `min_w` × `min_h`. Panels docked on those edges stay attached. NULL on
 failure.

 # Safety
 As for `ss_layout_drag_begin`.
 */
struct SsLayoutGesture *ss_layout_resize_begin(const char *scene_json,
                                               const char *id,
                                               double min_w,
                                               double min_h);

/*
 New frames for the pointer moved by (dx, dy) points since the gesture
 began (for a resize: the size change), as a JSON array of `{"id", "x",
 "y", "w", "h"}`. `snap` false (Option held) skips snapping. Free with
 `ss_string_free`; NULL if `gesture` is NULL.

 # Safety
 `gesture` must be NULL or live.
 */
char *ss_layout_gesture_update(const struct SsLayoutGesture *gesture,
                               double dx,
                               double dy,
                               bool snap);

/*
 Ends a gesture. NULL is a no-op.

 # Safety
 `gesture` must be NULL or a live handle not yet ended.
 */
void ss_layout_gesture_end(struct SsLayoutGesture *gesture);

/*
 For a scene (as in `ss_layout_drag_begin`): `{"docked": [ids docked to
 main], "constrain": [placements pulling off-screen panels back], "tidy":
 [placements straightening docked panels]}`. Free
 with `ss_string_free`; NULL on failure.

 # Safety
 `scene_json` must be NUL-terminated UTF-8.
 */
char *ss_layout_analyze(const char *scene_json);

/*
 New frames for a double-size change by `ratio` (2 or 0.5): the main
 panel's docked group keeps its shape around the main panel's top-left
 corner; other panels grow or shrink in place. JSON array of placements;
 free with `ss_string_free`; NULL on failure.

 # Safety
 `scene_json` must be NUL-terminated UTF-8.
 */
char *ss_layout_scale(const char *scene_json, double ratio);

/*
 Where to open panel `id`, given its remembered or default frame (x, y,
 w, h): that frame if it covers no open panel, else docked at the next
 free edge of the main panel's group, on a screen. JSON `{"x", "y", "w",
 "h"}`; free with `ss_string_free`; NULL on failure.

 # Safety
 `scene_json` and `id` must be NUL-terminated UTF-8.
 */
char *ss_layout_place(const char *scene_json,
                      const char *id,
                      double x,
                      double y,
                      double w,
                      double h);

/*
 The saved layout, `{"version", "panels": [{"id", "x", "y", "w", "h",
 "visible"}]}`, or "null" when none was saved. Free with `ss_string_free`.
 */
char *ss_layout_load(void);

/*
 Saves the layout (same JSON as `ss_layout_load` returns).

 # Safety
 `json` must be NUL-terminated UTF-8.
 */
enum SsStatus ss_layout_save(const char *json);

/*
 Resolves a skin for the UI as JSON (see core/crates/skin/src/resolve.rs,
 `ResolvedSkin`): image paths are absolute, `@token` colors resolved, and
 what the skin leaves out comes from the Default skin. `id_or_path` is an
 installed skin's id, an absolute path to an unpacked skin folder, or
 NULL/"" for the Default skin. NULL on failure (see
 `ss_last_error_message`). Free with `ss_string_free`.

 # Safety
 `id_or_path` must be NULL or NUL-terminated UTF-8.
 */
char *ss_skin_load(const char *id_or_path);

/*
 The skin chosen in the settings (`"skin"`), resolved as by
 `ss_skin_load`. If it no longer loads, the Default skin is returned with
 the reason first in `warnings`. Free with `ss_string_free`.
 */
char *ss_skin_load_current(void);

/*
 Validates a `.sskin` archive and installs it into the Skins folder
 (replacing a skin with the same id). Returns the installed skin's summary
 as JSON (`{"id", "name", "author", "version", "dir", "builtin", "error"}`),
 or NULL on failure with a message naming the file and problem. Free with
 `ss_string_free`.

 # Safety
 `archive_path` must be NUL-terminated UTF-8.
 */
char *ss_skin_install(const char *archive_path);

/*
 Installed skins as a JSON array of summaries (see `ss_skin_install`),
 the Default skin first. Free with `ss_string_free`.
 */
char *ss_skins_list(void);

/*
 Uninstalls a skin by id. The Default skin can't be removed.

 # Safety
 `id` must be NUL-terminated UTF-8.
 */
enum SsStatus ss_skin_remove(const char *id);

/*
 Validates a `.sskin` archive without installing it, for the install
 card: `{"id", "name", "author", "version", "description", "path",
 "preview" (a PNG of the main panel, or null), "warnings", "installed"
 (the installed skin it would replace, or null)}`. NULL on failure. Free
 with `ss_string_free`.

 # Safety
 `archive_path` must be NUL-terminated UTF-8.
 */
char *ss_skin_inspect(const char *archive_path);

/*
 A picture of a skin's main panel with sample content: the path of a
 cached PNG, as a JSON string. `id_or_path` as for `ss_skin_load`. Free
 with `ss_string_free`.

 # Safety
 `id_or_path` must be NULL or NUL-terminated UTF-8.
 */
char *ss_skin_preview(const char *id_or_path);

/*
 Checks an unpacked skin folder and writes it as a `.sskin` to
 `out_path`. Returns the skin's summary (see `ss_skin_install`; `dir` is
 the archive), or NULL with the problem. Free with `ss_string_free`.

 # Safety
 Both arguments must be NUL-terminated UTF-8.
 */
char *ss_skin_package(const char *dir, const char *out_path);

/*
 Creates a new skin folder `parent/name` from the Default skin (with its
 own id and a README guide) for a skin author. Returns its path as a
 JSON string, or NULL. Free with `ss_string_free`.

 # Safety
 Both arguments must be NUL-terminated UTF-8.
 */
char *ss_skin_create(const char *parent, const char *name);

/*
 A token (JSON string) that changes whenever a skin folder's files do,
 for reloading a skin while it's being made. NULL if the folder can't be
 read. Free with `ss_string_free`.

 # Safety
 `dir` must be NUL-terminated UTF-8.
 */
char *ss_skin_folder_stamp(const char *dir);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SOUND_SCRAPER_H */
