#ifndef SOUND_SCRAPER_H
#define SOUND_SCRAPER_H

/* Generated by cbindgen from core/crates/core/src/ffi.rs. Do not edit. */

#include <stdint.h>
#include <stdbool.h>

/*
 Recorder state as seen from C.
 */
typedef enum SsRecorderState {
  SS_RECORDER_STATE_IDLE = 0,
  SS_RECORDER_STATE_RECORDING = 1,
  SS_RECORDER_STATE_PAUSED = 2,
  SS_RECORDER_STATE_FINALIZING = 3,
} SsRecorderState;

/*
 Result of a fallible call. On `SS_STATUS_ERROR`, `ss_last_error_message`
 describes the failure.
 */
typedef enum SsStatus {
  SS_STATUS_OK = 0,
  SS_STATUS_ERROR = 1,
} SsStatus;

typedef enum SsRecorderEventKind {
  /*
   `state` changed.
   */
  SS_RECORDER_EVENT_KIND_STATE_CHANGED = 0,
  /*
   About 10 Hz while recording or paused: `elapsed_ms`, `peak`, `rms`.
   */
  SS_RECORDER_EVENT_KIND_PROGRESS = 1,
  /*
   A recording was finalized at `path`.
   */
  SS_RECORDER_EVENT_KIND_FINISHED = 2,
  /*
   Recording failed; see `message`.
   */
  SS_RECORDER_EVENT_KIND_ERROR = 3,
} SsRecorderEventKind;

/*
 Opaque list of apps from `ss_audio_apps_list`.
 */
typedef struct SsAudioAppList SsAudioAppList;

/*
 Opaque recorder handle. Create with `ss_recorder_create`, free with
 `ss_recorder_destroy`. Its functions may be called from any thread.
 */
typedef struct SsRecorder SsRecorder;

/*
 A recorder event. Pointers are valid only during the callback.
 */
typedef struct SsRecorderEvent {
  enum SsRecorderEventKind kind;
  enum SsRecorderState state;
  /*
   Recorded time, excluding pauses.
   */
  uint64_t elapsed_ms;
  /*
   Linear levels (0..1) over the last interval; 0 while paused.
   */
  float peak;
  float rms;
  /*
   UTF-8; non-NULL for `SS_RECORDER_EVENT_KIND_FINISHED` only.
   */
  const char *path;
  /*
   UTF-8; non-NULL for `SS_RECORDER_EVENT_KIND_ERROR` only.
   */
  const char *message;
} SsRecorderEvent;

/*
 Receives recorder events, on a recorder thread or the calling thread.
 It must return quickly and must not call back into the same recorder.
 */
typedef void (*SsRecorderCallback)(const struct SsRecorderEvent *event, void *user_data);

/*
 An app that can be recorded on its own. Strings are UTF-8 and owned by the
 list they came from.
 */
typedef struct SsAudioApp {
  uint32_t pid;
  const char *name;
  /*
   NULL when the process has no bundle ID.
   */
  const char *bundle_id;
  bool is_playing;
} SsAudioApp;

/*
 Outcome of `ss_capture_test_wav`. Free `path` with `ss_capture_report_free`.
 */
typedef struct SsCaptureReport {
  /*
   UTF-8 path of the WAV file that was written.
   */
  char *path;
  uint64_t frames;
  uint32_t sample_rate;
  uint16_t channels;
  /*
   Largest absolute sample; 0 means the recording was silent.
   */
  float peak;
} SsCaptureReport;

/*
 Input rates LAME accepts without resampling.
 */
#define SUPPORTED_RATES { 8000, 11025, 12000, 16000, 22050, 24000, 32000, 44100, 48000, }

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Core version as a NUL-terminated UTF-8 string with static lifetime.
 The caller must not free it.
 */
const char *ss_version(void);

/*
 Creates a recorder in the Idle state that saves to the default recordings
 folder. Never returns NULL.
 */
struct SsRecorder *ss_recorder_create(void);

/*
 Destroys a recorder, finalizing any recording in progress. NULL is a no-op.

 # Safety
 `recorder` must be NULL or a handle from `ss_recorder_create` that has
 not already been destroyed, with no other call on it in progress.
 */
void ss_recorder_destroy(struct SsRecorder *recorder);

/*
 Current state of `recorder`; Idle when `recorder` is NULL. Never blocks.

 # Safety
 `recorder` must be NULL or a live handle from `ss_recorder_create`.
 */
enum SsRecorderState ss_recorder_state(const struct SsRecorder *recorder);

/*
 Recorded time in milliseconds, excluding pauses. Never blocks.

 # Safety
 `recorder` must be NULL or a live handle from `ss_recorder_create`.
 */
uint64_t ss_recorder_elapsed_ms(const struct SsRecorder *recorder);

/*
 Sets (or with NULL, clears) the event callback. Only while Idle.

 # Safety
 `recorder` must be a live handle; `user_data` must stay valid, and be
 usable from any thread, until the callback is replaced or the recorder
 is destroyed.
 */
enum SsStatus ss_recorder_set_callback(struct SsRecorder *recorder,
                                       SsRecorderCallback callback,
                                       void *user_data);

/*
 Starts recording one app (`app_pid` non-zero) or all system audio
 (`app_pid` 0) to a new `.mp3.part` in the recordings folder. May block
 while macOS asks for the audio-capture permission; call off the UI thread.

 # Safety
 `recorder` must be NULL or a live handle from `ss_recorder_create`.
 */
enum SsStatus ss_recorder_start(struct SsRecorder *recorder, uint32_t app_pid);

/*
 Pauses: the file and encoder stay open and incoming audio is dropped.

 # Safety
 `recorder` must be NULL or a live handle from `ss_recorder_create`.
 */
enum SsStatus ss_recorder_pause(struct SsRecorder *recorder);

/*
 Resumes after `ss_recorder_pause`.

 # Safety
 `recorder` must be NULL or a live handle from `ss_recorder_create`.
 */
enum SsStatus ss_recorder_resume(struct SsRecorder *recorder);

/*
 Stops and finalizes (flush, Xing/LAME tag, ID3 tags, rename to `.mp3`).
 Blocks until done. On success `*out_path` (if not NULL) receives the
 file's UTF-8 path, to be freed with `ss_string_free`.

 # Safety
 `recorder` must be NULL or a live handle; `out_path` must be NULL or
 writable.
 */
enum SsStatus ss_recorder_stop(struct SsRecorder *recorder, char **out_path);

/*
 Finishes `.mp3.part` files left in the recordings folder by a crash.
 Returns how many were recovered, or -1 on error. Call at startup, before
 any recording starts.
 */
int32_t ss_recover_partial_recordings(void);

/*
 Frees a string returned by this library. NULL is a no-op.

 # Safety
 `s` must be NULL or a string from this library not already freed.
 */
void ss_string_free(char *s);

/*
 Message for the last `SS_STATUS_ERROR` returned on this thread. Valid until
 the next failing call on the same thread; the caller must not free it.
 */
const char *ss_last_error_message(void);

/*
 Apps with audio processes, those playing sound first. Free with
 `ss_audio_app_list_free`. Never returns NULL.
 */
struct SsAudioAppList *ss_audio_apps_list(void);

/*
 Number of apps in `list` (0 for NULL).

 # Safety
 `list` must be NULL or a live list from `ss_audio_apps_list`.
 */
size_t ss_audio_app_list_len(const struct SsAudioAppList *list);

/*
 App at `index`, or NULL when out of range. Valid until the list is freed.

 # Safety
 `list` must be NULL or a live list from `ss_audio_apps_list`.
 */
const struct SsAudioApp *ss_audio_app_list_get(const struct SsAudioAppList *list, size_t index);

/*
 Frees a list from `ss_audio_apps_list`. NULL is a no-op.

 # Safety
 `list` must be NULL or a list that has not already been freed.
 */
void ss_audio_app_list_free(struct SsAudioAppList *list);

/*
 Records `seconds` of audio to a WAV file in the recordings folder: one
 app's audio when `app_pid` is non-zero, otherwise all system audio.
 Blocks for the duration, so call it off the UI thread.

 # Safety
 `out_report` must point to writable memory for one `SsCaptureReport`.
 */
enum SsStatus ss_capture_test_wav(uint32_t app_pid,
                                  double seconds,
                                  struct SsCaptureReport *out_report);

/*
 Frees the strings inside a report filled by `ss_capture_test_wav`.

 # Safety
 `report` must be NULL or a report filled by `ss_capture_test_wav` that has
 not already been freed.
 */
void ss_capture_report_free(struct SsCaptureReport *report);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SOUND_SCRAPER_H */
