#ifndef SOUND_SCRAPER_H
#define SOUND_SCRAPER_H

/* Generated by cbindgen from core/crates/core/src/ffi.rs. Do not edit. */

#include <stdint.h>
#include <stdbool.h>

/*
 Recorder state as seen from C.
 */
typedef enum SsRecorderState {
  SS_RECORDER_STATE_IDLE = 0,
  SS_RECORDER_STATE_RECORDING = 1,
  SS_RECORDER_STATE_PAUSED = 2,
  SS_RECORDER_STATE_FINALIZING = 3,
} SsRecorderState;

/*
 Opaque recorder handle. Create with `ss_recorder_create`, free with
 `ss_recorder_destroy`.
 */
typedef struct SsRecorder SsRecorder;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Core version as a NUL-terminated UTF-8 string with static lifetime.
 The caller must not free it.
 */
const char *ss_version(void);

/*
 Creates a recorder in the Idle state. Never returns NULL.
 */
struct SsRecorder *ss_recorder_create(void);

/*
 Destroys a recorder. Passing NULL is a no-op.

 # Safety
 `recorder` must be NULL or a handle from `ss_recorder_create` that has
 not already been destroyed.
 */
void ss_recorder_destroy(struct SsRecorder *recorder);

/*
 Current state of `recorder`; Idle when `recorder` is NULL.

 # Safety
 `recorder` must be NULL or a live handle from `ss_recorder_create`.
 */
enum SsRecorderState ss_recorder_state(const struct SsRecorder *recorder);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SOUND_SCRAPER_H */
