import React, { useMemo, useState } from 'react';
import {
  FlatList,
  Platform,
  Pressable,
  StyleSheet,
  Text,
  View,
} from 'react-native';

import { getCoreVersion } from './native/SoundScraper';
import { usePanelStyles } from './panelTheme';
import { colors } from './theme';

type Pkg = {
  name: string;
  version: string;
  license: string;
  repository?: string | null;
  texts: string[];
  note?: string;
};
type LicenseData = {
  lame: Pkg;
  rust: Pkg[];
  js: Pkg[];
  texts: Record<string, string>;
};

// Generated by scripts/gen-licenses.py.
const data: LicenseData = require('./licenses.json');

type Props = {
  /** Shows a heading with Done (the overlay in the plain UI). */
  onClose?: () => void;
  textStyle: object;
};

/** App info and third-party licenses (LAME's LGPL notice first). */
export function AboutPanel(props: Props): React.JSX.Element {
  const { textStyle } = props;
  const panel = usePanelStyles();
  const [open, setOpen] = useState<string>();
  const rows = useMemo(
    () => [
      { kind: 'header' as const, key: 'h-lame', title: 'MP3 encoder' },
      { kind: 'pkg' as const, key: 'lame', pkg: data.lame },
      {
        kind: 'header' as const,
        key: 'h-rust',
        title: `Rust crates (${data.rust.length})`,
      },
      ...data.rust.map(p => ({
        kind: 'pkg' as const,
        key: `r-${p.name}-${p.version}`,
        pkg: p,
      })),
      {
        kind: 'header' as const,
        key: 'h-js',
        title: `JavaScript packages (${data.js.length})`,
      },
      ...data.js.map(p => ({
        kind: 'pkg' as const,
        key: `j-${p.name}-${p.version}`,
        pkg: p,
      })),
    ],
    [],
  );

  return (
    <View style={styles.panel}>
      {props.onClose && (
        <View style={styles.header}>
          <Text style={[styles.heading, textStyle]}>About Sound Scraper</Text>
          <Pressable onPress={props.onClose} testID="close-about">
            <Text style={[styles.link, panel.link]}>Done</Text>
          </Pressable>
        </View>
      )}
      <Text style={[styles.meta, textStyle]}>Core v{safeVersion()}</Text>
      <Text style={[styles.meta, textStyle]}>
        Sound Scraper is built with open-source software. Select a component to
        read its license.
      </Text>
      <FlatList
        data={rows}
        keyExtractor={r => r.key}
        initialNumToRender={30}
        renderItem={({ item }) =>
          item.kind === 'header' ? (
            <Text style={[styles.section, textStyle]}>{item.title}</Text>
          ) : (
            <View>
              <Pressable
                onPress={() =>
                  setOpen(o => (o === item.key ? undefined : item.key))
                }
                style={styles.pkg}
              >
                <Text style={[styles.pkgName, textStyle]} numberOfLines={1}>
                  {item.pkg.name} {item.pkg.version}
                </Text>
                <Text style={[styles.pkgLicense, textStyle]} numberOfLines={1}>
                  {item.pkg.license}
                </Text>
              </Pressable>
              {item.pkg.note && (
                <Text style={[styles.note, textStyle]}>{item.pkg.note}</Text>
              )}
              {open === item.key && (
                <View style={styles.textBox}>
                  {item.pkg.repository ? (
                    <Text selectable style={[styles.repo, textStyle]}>
                      {item.pkg.repository}
                    </Text>
                  ) : null}
                  {item.pkg.texts.length === 0 ? (
                    <Text style={[styles.licenseText, textStyle]}>
                      This package declares the {item.pkg.license} license but
                      doesn't include a license file.
                    </Text>
                  ) : (
                    item.pkg.texts.map(t => (
                      <Text
                        key={t}
                        selectable
                        style={[styles.licenseText, textStyle]}
                      >
                        {data.texts[t]}
                      </Text>
                    ))
                  )}
                </View>
              )}
            </View>
          )
        }
      />
    </View>
  );
}

function safeVersion(): string {
  try {
    return getCoreVersion();
  } catch {
    return '?';
  }
}

const styles = StyleSheet.create({
  panel: { flex: 1 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  heading: { fontSize: 18, fontWeight: '600' },
  link: { color: colors.accent, fontSize: 13 },
  meta: { fontSize: 12, opacity: 0.7, marginBottom: 6 },
  section: { fontSize: 13, fontWeight: '600', marginTop: 14, marginBottom: 4 },
  pkg: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 3,
    gap: 8,
  },
  pkgName: { fontSize: 12, flexShrink: 1 },
  pkgLicense: { fontSize: 11, opacity: 0.6 },
  note: { fontSize: 11, opacity: 0.8, marginBottom: 6 },
  textBox: {
    padding: 8,
    marginBottom: 6,
    borderRadius: 4,
    backgroundColor: '#8881',
  },
  repo: { fontSize: 11, color: colors.accent, marginBottom: 6 },
  licenseText: {
    fontSize: 10,
    fontFamily: Platform.select({ windows: 'Consolas', default: 'Menlo' }),
    opacity: 0.85,
    marginBottom: 6,
  },
});
